### ISSUE TITLE
Keep a CHANGELOG

### ISSUE THREAD

**Issue by bessey** [github/graphql-client#144]
This project is pretty popular now, it would be great if at least going forward a CHANGELOG.md of some variety was kept. Or perhaps GitHub release descriptions.

**Comment by josh** [comment]
We'll keep this in mind—thanks!

**Comment by opsidao** [comment]
626 starts, 89 forks, 526,934 downloads in rubygems... I think you guys have already earned enough popularity to seriously consider doing this sooner rather than later, it's a real pain in the butt when you guys release a new version and we're left wondering _"will this break my production app in some weird way? I guess I'll have to check the commit history and trust my test suite"_, which is not ideal.

**Comment by etherbob** [comment]
This gem is very helpful. Any chance of revisiting this?
