### ISSUE TITLE
Testing guide

### ISSUE THREAD

**Issue by bessey** [github/graphql-client#33]
Are there any suggestions for how (remote fetch) testing should be done? In my JS apps I use [apollo graphql-tools](https://github.com/apollostack/graphql-tools) to use a stored GraphQL schema to build a server that will only mock valid requests for the given schema. 

It seems like something comparable could be built in Ruby land. In the meantime I guess I'll stub the HTTP responses, but it seems one loses the benefit of schema based validation in that case.

**Comment by josh** [comment]
> In the meantime I guess I'll stub the HTTP responses, but it seems one loses the benefit of schema based validation in that case.

HTTP mocks definitely work. You could also make a `GraphQL::Schema` that uses resolvers against fixture data and point the client at that.

That's basically how I'm writing the tests for the library itself.

See https://github.com/github/graphql-client/blob/master/test/test_client_fetch.rb

Thanks for the question!

**Comment by joffotron** [comment]
@josh Seeing as the pattern used in this library is to define the Schema, Client, etc as constants, (in order to have static queries) what do you recommend we do to disable real HTTP calls for our test suite? 

Using `const_set` seems pretty icky. The pattern I have in my app for other APIs is to stub out the call to the external thing, so I'm not making slow, external calls for any application code that touches my GraphQL client, and only enabling it for specs specifically concerned with my API client class.

Thoughts?

**Comment by josh** [comment]
> Using const_set seems pretty icky.

That's only needed internally since this client generates dynamic queries which applications shouldn't be doing in practice.

> The pattern I have in my app for other APIs is to stub out the call to the external thing, so I'm not making slow, external calls for any application code that touches my GraphQL client, and only enabling it for specs specifically concerned with my API client class.

I'd suggest just setting a custom `execute` class that is an offline mock. https://github.com/github/graphql-client/blob/9d1563d1db2f75c1f5a6c96415bb1355d0d7faa9/lib/graphql/client.rb#L75

**Comment by joffotron** [comment]
Hrm. I thought I had replied to this days ago, Mustn't have hit the submit button ;)

Anyway, this is a simplified version of what we are doing:
https://gist.github.com/joffotron/dde047f4158fce3bdbe615484c96377f
and how we are stubbing out the service for testing.

Is this the kind of pattern you are using in production apps?

Additionally, we hit a case where we deployed our app without the GRAPHQL_ENDPOINT env var set (our GraphQL stuff was inactive behind a feature flag), but because the client init code is run on classload, it exploded. Granted, this is a separate issue - I'd be happy to open a separate discussion on how this stuff should be approached?

**Comment by josh** [comment]
Maybe use a class `attr_accessor` instead of a constant? You can initialize a new client during tests:

``` ruby
# test env
MyService::API.graphql_client = GraphQL::Client.new(schema: MyService::API::SCHEMA, execute: StubStockroomAdapter)
```

**Comment by aliahmed922** [comment]
And maybe if someone is trolling for a more advanced version of what @joffotron proposed. Give a shot to this [one](https://gist.github.com/aliahmed922/3db3558c164e8cace7937c01c01c9571).

**Comment by devneillza** [comment]
Thanks for this @joffotron @aliahmed922 🙌🏻
